# Generated by Django 4.1 on 2022-09-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cus_ser', '0005_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('in door', 'in door'), ('out door', 'out door')], max_length=100, null=True),
        ),
    ]
