# Generated by Django 4.1 on 2022-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cus_ser', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('outForDelivery', 'outForDelivery'), ('delivered', 'delivered')], max_length=200, null=True),
        ),
    ]
